from enum import Enum


class Metric(Enum):
    Accuracy = 'Accuracy'
    AUC = 'AUC'
    BinaryCrossentropy = 'BinaryCrossentropy'
    BinaryAccuracy = 'BinaryAccuracy'
    CategoricalAccuracy = ' CategoricalAccuracy'
    CategoricalCrossentropy = 'CategoricalCrossentropy'
    CategoricalHinge = 'CategoricalHinge'
    CosineSimilarity = 'CosineSimilarity'
    FalseNegatives = 'FalseNegatives'
    FalsePositives = 'FalsePositives'
    Hinge = 'Hinge'
    LogCoshError = 'LogCoshError'
    Mean = 'Mean'
    MeanAbsoluteError = 'MeanAbsoluteError'
    MeanAbsolutePercentageError = 'MeanAbsoluteError'
    MeanIoU = 'MeanIoU'
    MeanRelativeError = 'MeanRelativeError'
    MeanSquaredError = 'MeanSquaredError'
    MeanTensor = 'MeanTensor'
    Poisson = 'Poisson'
    Precision = 'Precision'
    PrecisionAtRecall = 'PrecisionAtRecall'
    Recall = 'Recall'
    RecallAtPrecision = 'RecallAtPrecision'
    RootMeanSquaredError = 'RootMeanSquaredError'
    SensitivityAtSpecificity = 'SensitivityAtSpecificity'
    SparseCategoricalAccuracy = 'SparseCategoricalAccuracy'
    SparseCategoricalCrossentropy = 'SparseCategoricalCrossentropy'
    SparseTopKCategoricalAccuracy = 'SparseTopKCategoricalAccuracy'
    SpecificityAtSensitivity = 'SpecificityAtSensitivity'
    SquaredHinge = 'SquaredHinge'
    TopKCategoricalAccuracy = 'TopKCategoricalAccuracy'
    TrueNegatives = 'TrueNegatives'
    TruePositives = 'TruePositives'