package bean;

public enum Metric {
        Accuracy,
        AUC,
        BinaryCrossentropy,
        BinaryAccuracy,
        CategoricalAccuracy,
        CategoricalCrossentropy,
        CategoricalHinge,
        CosineSimilarity,
        FalseNegatives,
        FalsePositives,
        Hinge,
        LogCoshError,
        Mean,
        MeanAbsoluteError,
        MeanAbsolutePercentageError,
        MeanIoU,
        MeanRelativeError,
        MeanSquaredError,
        MeanTensor,
        Poisson,
        Precision,
        PrecisionAtRecall,
        Recall,
        RecallAtPrecision,
        RootMeanSquaredError,
        SensitivityAtSpecificity,
        SparseCategoricalAccuracy,
        SparseCategoricalCrossentropy,
        SparseTopKCategoricalAccuracy,
        SpecificityAtSensitivity,
        SquaredHinge,
        TopKCategoricalAccuracy,
        TrueNegatives,
        TruePositives
    }
